### ISSUE TITLE
EME 2.3.64 makes 

### ISSUE THREAD

**Issue by robertknotek** [liedekef/events-made-easy#156] opened 2023-04-20 09:42 UTC
Es gab einen kritischen Fehler auf deiner Website.

[Erfahre mehr über die Problembehandlung in WordPress.](https://wordpress.org/documentation/article/faq-troubleshooting/)

I used [eme_events] and [eme_events scope=past--yesterday order=DESC]

https://www.patientinnenportal.at/veranstaltungen/ausblick/
https://www.patientinnenportal.at/veranstaltungen/rueckblick/

**To Reproduce**
2. Set '...' to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**
Display Events

**Online Demo**
https://www.patientinnenportal.at/veranstaltungen/ausblick/
https://www.patientinnenportal.at/veranstaltungen/rueckblick/
**Log output**
If applicable, check your php error logfile and add php errors here

**Additional context**
This behavior started after upgrade from an older version to 2.63.64

**Comment by liedekef** [comment] 2023-04-21 07:17
no reaction, no log and not reproducable, so closing.

**Closed by liedekef** 2023-04-21 07:17 UTC

**Comment by robertknotek** [comment] 2023-04-21 08:23
Sorry for this delay.

I had yesterday, no time left to analyze.

The first thing i found

If i switch off the Plugin JCHoptimice the error diapered, but there is no display of events.


10:17:34.795
Anfrage für Zugriff auf Cookies oder Speicher für "<URL>" wurde blockiert, weil sie von einem Element zur Aktivitätenverfolgung (Tracker) stammt und das Blockieren von Seitenelementen aktiviert ist. 14
10:17:34.931 JQMIGRATE: Migrate is installed, version 3.4.0 [jquery-migrate.min.js:2:970](https://www.patientinnenportal.at/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.4.0)
10:17:35.018 downloadable font: no supported format found (font-family: "Genericons" style:normal weight:400 stretch:100 src index:1) source: (end of source list)
10:17:35.252 downloadable font: no supported format found (font-family: "Genericons" style:normal weight:400 stretch:100 src index:1) source: (end of source list)
10:17:35.754 Error: An unexpected error occurred 2 undefined:63:885
10:17:36.083
Einige Cookies verwenden das empfohlene "SameSite"-Attribut inkorrekt. 2
10:17:39.471 InstallTrigger sollte nicht mehr verwendet werden und wird in Zukunft entfernt. [sdk.js:63:884](https://connect.facebook.net/en_US/sdk.js?hash=abdbd61fb99cd055147fd316e03734e8)
10:17:39.471 onmozfullscreenchange sollte nicht mehr verwendet werden. [sdk.js:63:884](https://connect.facebook.net/en_US/sdk.js?hash=abdbd61fb99cd055147fd316e03734e8)
10:17:39.471 onmozfullscreenerror sollte nicht mehr verwendet werden. [sdk.js:63:884](https://connect.facebook.net/en_US/sdk.js?hash=abdbd61fb99cd055147fd316e03734e8)


With JCHoptimice on


10:08:46.612
Anfrage für Zugriff auf Cookies oder Speicher für "<URL>" wurde blockiert, weil sie von einem Element zur Aktivitätenverfolgung (Tracker) stammt und das Blockieren von Seitenelementen aktiviert ist. 21
10:08:46.767 JQMIGRATE: Migrate is installed, version 3.4.0 [jquery-migrate.min.js:2:970](https://www.patientinnenportal.at/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.4.0)
10:08:46.899 downloadable font: no supported format found (font-family: "Genericons" style:normal weight:400 stretch:100 src index:1) source: (end of source list)
10:08:47.210
Uncaught
Object { message: "invalid version specified", innerError: undefined, stack: "" }
​
innerError: undefined
​
message: "invalid version specified"
​
stack: ""
​
<prototype>: Object { constructor: b(b, c)
, stack: "" }
[sdk.js:63:885](https://connect.facebook.net/en_US/sdk.js?hash=abdbd61fb99cd055147fd316e03734e8)
10:08:47.331
Einige Cookies verwenden das empfohlene "SameSite"-Attribut inkorrekt. 11
10:08:48.163 YT API init check [ytprefs.min.js:13:459](https://www.patientinnenportal.at/wp-content/plugins/youtube-embed-plus-pro/scripts/ytprefs.min.js?ver=14.1.6.1)
10:08:49.176 YT API init check 3 [ytprefs.min.js:13:459](https://www.patientinnenportal.at/wp-content/plugins/youtube-embed-plus-pro/scripts/ytprefs.min.js?ver=14.1.6.1)
10:08:52.150 downloadable font: no supported format found (font-family: "Genericons" style:normal weight:400 stretch:100 src index:1) source: (end of source list)

Switching PHP to debug:

till now i can't find anything in logfiles ..... keep trying.

I'm using PHP 8.1 but 8.2 is available

Kind regards

**Comment by liedekef** [comment] 2023-04-21 08:57
These are javascript errors and the error itself seems to be generated by another plugin. I never liked optimizers ... but exclude the EME plugin path from optimizing.
I tried your shortcode, works fine (exact copy/paste done even)

**Comment by robertknotek** [comment] 2023-04-21 08:58
OK... I Try.

But without Optimicer the error disappeared and there is no display of data

**Comment by liedekef** [comment] 2023-04-21 09:17
Your side somehow produces an "Internal Server Error" ==> you need to find the reason for that in your logs. I also use php 8.x without issues, so that's no problem.

**Comment by robertknotek** [comment] 2023-04-21 14:37
I excluded now the pages from Optimicer....

It seems to work
