### ISSUE TITLE
Issue with mailing

### ISSUE THREAD

**Issue by TommieNL** [liedekef/events-made-easy#600] opened 2024-07-17 14:47 UTC
Hello,

I'm trying to send an event related e-mail.

Ive selected the event
All attendees
All registered persons
A test subject
A test Message
A mailing name

When sending a test message i'm getting the warning: Enter both subject and message for the email to be sent.

Extra: when re-using an old mailing it works, but I cannot change the body of the text (only the subject).

What am I doing wrong? I'm at 2.4.50

**Comment by TommieNL** [comment] 2024-07-17 15:08
Note: by creating a template and using that i'm succesful with sending an e-mail.

**Comment by liedekef** [comment] 2024-07-17 16:08
Concerning the subject/content: it seems this can be related to the text-part not being initialized correctly. I could replicate it once ... switch from html->text view and see that isn't empty then. I'll check that some more here too.
Concerning the "0 e-mails": it seems the count is wrong before the emails are sent, but it is correct when the actual sending takes place :-) Reason is that I no longer insert the individual mails before the mail goes out (because I needed to recount/recheck the recipients before sending anyway), but it means here the count is wrong. I can reproduce that so I'll come up with a fix :-)

**Comment by liedekef** [comment] 2024-07-17 16:16
The count issue is fixed here:
https://github.com/liedekef/events-made-easy/commit/7dd5bb7c1894455ea22a783d8db6eb3eeded1429

**Comment by TommieNL** [comment] 2024-07-17 16:26
Thanks for the quick reply as always!

I was able to send a mail when adding it to templates and using those. I've leaved the data empty to send it direct. But it remains at status "plannend". This is not something I recognize from before (it always sended directly and added it to the main queue)

**Comment by TommieNL** [comment] 2024-07-17 16:49
Hmm maybe I was inpatient... the queue is full now!

**Comment by liedekef** [comment] 2024-07-17 18:56
For now I'll close this, new version with the mentioned fix released. If you have more issues with the test email, please report them in a new issue.

**Closed by liedekef** 2024-07-17 18:56 UTC

**Comment by liedekef** [comment] 2024-07-19 11:48
good news: I also found out the reason of the "Enter both subject and message for the email to be sent" issue. I renamed an option but forgot to update certain variables to the new name, causing this issue. I'll release another version to fix this.

**Comment by TommieNL** [comment] 2024-07-19 12:04
> good news: I also found out the reason of the "Enter both subject and message for the email to be sent" issue. I renamed an option but forgot to update certain variables to the new name, causing this issue. I'll release another version to fix this.

Awesome @liedekef many thanks
