### ISSUE TITLE
‘Contact Person Booking Made Email Body & Subject' not translating to other languages

### ISSUE THREAD

**Issue by sonalvrioss-svyatos** [liedekef/events-made-easy#60] opened 2023-02-03 13:05 UTC
**Describe the bug**
Multi-language tags in ‘Contact Person Booking Made Email Body & Subject' template not translating for Chinese.
Subject:
![image](https://user-images.githubusercontent.com/101639308/216610388-07b8bd1c-44f4-4b10-b1f1-3a9149126757.png)

Body:
![image](https://user-images.githubusercontent.com/101639308/216610115-9f327158-cebf-4e71-84e5-f0d70697551a.png)

**To Reproduce**
1. Add language tags to ‘Contact Person Booking Made Email Body & Subject' template
2. Register for event in Chinese language
3. See error

**Expected behavior**
Email should display the Chinese language for all items.

**Template**
Subject Template:
```
[:en]New registration for 'Equanimity Hybrid Course'[:zh]'平常心混合课程' 的新预订[:]
```

Body Template:
```
[:en]
#_PERSONFULLNAME (#_PERSONEMAIL) wants to register #_MULTIBOOKING_SEATS seat(s) for 'Equanimity Hybrid Course'.
<BR /><BR />
The details are as follows:
<BR />
#_MULTIBOOKING_DETAILS_TEMPLATE{36}
<BR /><BR />
Now the following seats are still available:
#_MULTIBOOKING_DETAILS_TEMPLATE{38}
<BR /><BR />
With Metta,
Events Manager
[:zh]
#_PERSONFULLNAME（#_PERSONEMAIL）将在 ‘平常心混合课程’ 预订 #_MULTIBOOKING_SEATS 个座位。
<BR /><BR />
详情如下：
<BR />
#_MULTIBOOKING_DETAILS_TEMPLATE{36}
<BR /><BR />
座位空缺如下：
#_MULTIBOOKING_DETAILS_TEMPLATE{38}
<BR /><BR />
祝安康快乐，
活动经理
[:]
```

**Comment by sonalvrioss-svyatos** [comment] 2023-02-04 00:27
> 

I tested it multiple times today and all my contact person emails are in English. I don't think something's wrong with Polylang + Loco because the registrant received all the emails in Chinese.

Registrant's emails:
![image](https://user-images.githubusercontent.com/101639308/216734655-a514f334-9b72-44f0-be2a-ca538a1ec9ba.png)

Contact person's emails:
![image](https://user-images.githubusercontent.com/101639308/216734693-703c5377-f612-48de-94f1-71516dec24e2.png)

What other settings, other than templates, can I check for proper translations?

**Comment by liedekef** [comment] 2023-02-04 20:44
Translation of dates is done through php, not EME.
But I think something else is wrong ... this message is clearly translated in EME:

`                        $ret_string .= "<div class='eme-message-success eme-rsvp-message-success'>" . __( 'Thank you for confirming these bookings.', 'events-made-easy' ) . '</div>';`

So if that translation is not coming through, something else is not working as expected (not EME). So several questions:
- how do you switch languages in polylang? 
- what do you mean with glotpress? Is that your local translation installation?

What are your polylang url settings? See:
![image](https://user-images.githubusercontent.com/75667/216788843-c2ef7fb6-856d-48bf-afaa-8fe06991c509.png)

**Comment by liedekef** [comment] 2023-02-04 20:45
And since polylang seems extremely complicated to me, can you put up a test website (not live) and provide me with an account to test? Also: make sure you can reproduce the problem on the test site and provide the simplest scenario for me to test.

**Comment by sonalvrioss-svyatos** [comment] 2023-02-05 22:54
1) This is from Polylang:

```The language is either set by the language code in URL, or you can use a different sub-domain or domain per language.```

My registration forms are 2 different posts with one set to English and the other set to Chinese. There is also a setting to link these 2 posts together. To switch languages, there is a widget at the top right hand corner to do so.
 
You can go to my test website/web page to see the [registration forms](https://dev.refugeindhamma.com/recollection-of-the-buddha-meditation-course-registration-mar-2023/).
 
2) I mean the plugin's translation handled by Wordpress. Not sure what it's called. I see the names "Polyglot", "Glotpress" in the documentation.

3) Polylang's URL settings
![image](https://user-images.githubusercontent.com/101639308/216850546-28f80fcb-6c67-4791-933d-8234e0b7fcc1.png)

**Comment by sonalvrioss-svyatos** [comment] 2023-02-06 14:49
I'm having problems with my email provider. Their webmail server is taking very long to load so I can't access the emails sent from the test server. I will update once their server is back to normal.

**Comment by liedekef** [comment] 2023-02-06 14:52
you can also look in the EME email-management menu, tab "sent emails", all emails from EME are kept there.
I do see that there are translation tags around the person name (in that tab), how/why did you do that?

**Comment by liedekef** [comment] 2023-02-06 15:00
btw: I clicked on a link in the mail (assuming it is unsubscribe or so) and got a bunch of chine characters back, so it seems ok for me :-)

**Comment by sonalvrioss-svyatos** [comment] 2023-02-06 15:04
> you can also look in the EME email-management menu, tab "sent emails", all emails from EME are kept there. I do see that there are translation tags around the person name (in that tab), how/why did you do that?

It's because Chinese names are in the format LASTNAME + FIRSTNAME, whereas for English names, it is in the format FIRSTNAME + LASTNAME.

**Comment by sonalvrioss-svyatos** [comment] 2023-02-06 15:07
It is working now! Thanks so much!
![image](https://user-images.githubusercontent.com/101639308/217007583-3eca574c-cbe1-4f6e-a3a8-9bd462a36b29.png)

Any changes in code to prevent this from happening again?

**Comment by liedekef** [comment] 2023-02-06 15:13
In fact this is not an EME issue but an polylang issue. As I said in my mail:

```
The actual problem is that the special events page is "linked" to english. Best to do here:

- delete the special events page
- disable polylang
- create new events page
- enable polylang
- set the new page in the EME options (Events tab) settings

Since the page is then not linked to a language, it should use the language of choice at that moment.
```
Also:
`I went a little further and added code to EME that will remove the polylang language if set to it. So that should solve it for future cases :-) . In theory polylang should just provide an option to remove the language for specific pages, as I can't start including code for each translation plugin myself. In that case, the workaround as above is also ok.
`
However: it might be that one needs to refresh the rewrite rules if the language ever gets added again, we'll see that when it happens again.

**Comment by liedekef** [comment] 2023-02-06 15:35
The code will be in the next version of EME (and is on your dev-site).
Now: does this mean that the name translation is incorrect, or just stored/displayed wrong in EME?

**Comment by liedekef** [comment] 2023-02-06 15:55
And while I'm at it, this info on polylang was already in the plugin compatibility document:
https://www.e-dynamics.be/wordpress/compatibility-with-other-plugins/
That would've saved us some time ... :-)

**Comment by sonalvrioss-svyatos** [comment] 2023-02-07 00:22
I will report this issue to Polylang and see if they can do anything about it.

**Comment by sonalvrioss-svyatos** [comment] 2023-02-07 00:52
> The code will be in the next version of EME (and is on your dev-site). Now: does this mean that the name translation is incorrect, or just stored/displayed wrong in EME "sent email" tab?

In the "Email Templates" Settings, if I do not use the language tags and using First + Last:
![image](https://user-images.githubusercontent.com/101639308/217119771-07cd5d8b-4799-484a-9695-3f4dcea35337.png)

The email I receive will also be First + Last:
![image](https://user-images.githubusercontent.com/101639308/217119846-c46103a8-af6c-45bf-a450-8cd8cea8a2da.png)

But if I put the language tags like this:
![image](https://user-images.githubusercontent.com/101639308/217120020-9d3a5e23-85b5-4a39-843a-12ce707a74ac.png)

Then, the name for Chinese can be displayed correctly, i.e. Last + First:
![image](https://user-images.githubusercontent.com/101639308/217120203-9a4b56ea-1b23-4124-81f3-83c05114a679.png)

Is this what you are asking?

**Comment by liedekef** [comment] 2023-02-07 08:21
It is indeed from "Set emails". I've fixed the code now for all usage of the full name. Next version will fix that :-)
Now the gdpr issue ...

**Closed by liedekef** 2023-02-07 08:21 UTC
