### ISSUE TITLE
Viewing location page gives syntax error

### ISSUE THREAD

**Issue by TimB111** [liedekef/events-made-easy#273] opened 2023-08-19 00:26 UTC
When trying to view a location page it gives this error:
`Parse error: syntax error, unexpected ':', expecting ')' in /home/mysite.com/wp-content/plugins/events-made-easy/eme-filters.php on line 231`

1. Go to EME > Locations > in list of locations click "View location" for one location in the list.

**Comment by liedekef** [comment] 2023-08-19 08:32
Are you sure your webserver is using php 8? This error indicates that is not the case

**Comment by TimB111** [comment] 2023-08-19 22:38
The site was on PHP 7.4 and I changed it to PHP 8.2 but the EME location page wasn't working with either PHP version. I think you're right, I tried changing the PHP version to 7.4 and it gives the same error message:
`PHP Parse error: syntax error, unexpected ':', expecting ')' in /home/mysite.com/wp-content/plugins/events-made-easy/eme-filters.php on line 231`

But after changing the PHP version to 8.2 the page doesn't load at all. The browser shows the page as loading but it's blank and eventually times out.

I'm using WordPress 6.3, EME 2.4.5, PHP 8.2.

**Comment by liedekef** [comment] 2023-08-20 06:31
Then you need to check the server php logfiles for info. A blank page can mean just about anything.

**Comment by TimB111** [comment] 2023-08-20 22:17
I checked the php error log on the web server and nothing is being written to the log. I checked this with the hosting company support and they confirmed that nothing is being written when the PHP version is 8.2 and trying to load this single location page. The browser just keeps waiting to load but nothing loads, and the page times out.

I've disabled every plugin except EME, so there's no issue with any other plugin. I can view the events list on the live site, and a single event page, and the locations map. Just can't view a single location page.

When I disable EME, the single location page loads and shows "This page is used by Events Made Easy. Etc...".

**Comment by liedekef** [comment] 2023-08-21 09:14
A blank page always indicates some kind of error (most probably a php memory issue). I can't reproduce that here, so unless you provide reproducable steps + logfile output (related to EME) there's not much I can do.

**Comment by liedekef** [comment] 2023-08-21 09:42
Also, check this for blank page hints in WP: https://www.inmotionhosting.com/support/edu/wordpress/my-wordpress-site-is-displaying-a-blank-page/ (or google "wordpress blank page")

**Comment by liedekef** [comment] 2023-08-21 11:32
And: put WP temprary in debug mode while the issue occurs, it might give more info.

**Comment by TimB111** [comment] 2023-08-21 15:22
I've taken these steps:

1. Put WP into debug mode by adding these lines to wp-config.php
`define( 'WP_DEBUG', true);
define( 'WP_DEBUG_LOG', true );`

2. I've set the php.ini to display errors. Here is the cpanel php.ini file:
`allow_url_fopen = Off
display_errors = On
enable_dl = Off
file_uploads = On
max_execution_time = 300
max_input_time = 600
max_input_vars = 2500
memory_limit = 1024M
post_max_size = 200M
session.gc_maxlifetime = 1440
session.save_path = "/var/cpanel/php/sessions/ea-php82"
upload_max_filesize = 200M
zlib.output_compression = Off`

3. All plugins disabled except EME.

4. I've changed the theme from Twenty Twenty-One to Twenty Twenty-Three to see if there was an issue with the theme. The single location page still doesn't load, there's still a very long wait, but instead of displaying a blank page it now displays a 503 error.
`Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Additionally, a 503 Service Unavailable error was encountered while trying to use an ErrorDocument to handle the request.`

5. I've tried to load the page in Chrome, Firefox and Vivaldi browsers.

Still, nothing is being written to the site's php error log file.

**Comment by liedekef** [comment] 2023-08-23 10:54
No further feedback here ... so closing for now

**Closed by liedekef** 2023-08-23 10:54 UTC
Labels: feedback required
