### ISSUE TITLE
Error when update from 2.3.28 to 2.3.29

### ISSUE THREAD

**Issue by f14m07** [liedekef/events-made-easy#1] opened 2022-12-31 09:52 UTC
Hi,
I get this error when I update from backend WP 
 ( ! ) Parse error: syntax error, unexpected token "," in /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-content/plugins/events-made-easy/events-manager.php on line 2089

**Comment by liedekef** [comment] 2022-12-31 10:05
Weird … I’m running 2.3.29 on all my sites and no issue. How are you doing the update? Because in fact in the “main” branch of EME there was a typo that I just fixed (but not in the released version)

**Comment by liedekef** [comment] 2022-12-31 10:28
Closing as non-reproducable for now (discussion ongoing at https://www.e-dynamics.be/wordpress/forums/topic/error-when-update-from-2-3-28-to-2-3-29/

**Closed** 2022-12-31 10:29 UTC
Labels: bug, question
