### ISSUE TITLE
Deleting "Pending Bookings" also automatically deletes "Approved Bookings" and "Events"

### ISSUE THREAD

**Issue by refugeindhamma** [liedekef/events-made-easy#196] opened 2023-06-09 11:33 UTC
**Describe the bug**
When I deleted a recurring "Pending Booking" of 19 events from 1 registrant:
1) All the "Approved Bookings" from the same recurring event were deleted at the same time;
2) All the recurring events from the same event were deleted at the same time.

**Expected behavior**
Deleting "Pending Bookings" should not affect "Approved Bookings" and "Events".

**Additional context**
I tried to replicate it on my test server but unable to do so. Not sure what is wrong.

**Comment by liedekef** [comment] 2023-06-09 18:44
Deleting bookings never delete events or anything else. According to your description, it seems like you deleted the recurrent events themselves ... If unable to reproduce, I'm currently going to close this. Feel free to reopen if you can reproduce it reliably.

**Closed by liedekef** 2023-06-09 18:44 UTC
