### ISSUE TITLE
Issue with the payment button

### ISSUE THREAD

**Issue by f14m07** [liedekef/events-made-easy#601] opened 2024-07-17 15:52 UTC
**Describe the bug**
The issue is on the Membership payment page. When you click the button, nothing happens

**To Reproduce**
1- Go to the membership page "https://vogue-et-reve.fr/adhesion-eme/"
2 - Complete the form and the button "Valider"
3 - Follow the link to pay
4 - Click the button on the Membership payment page

**Expected behavior**
It is expected to go to the stripe payment form page

**Screenshots**
But nothing appeared. I have an other page where the member may renew and it is the same issue with button as if there is no URL to reach.
![copyscreen](https://github.com/user-attachments/assets/0f0a6191-8399-4a7f-9020-900603977cd6)

**Online Demo**
No link
**Log output**
No error in the php error file. No error in the console

**Version info**
PHP version:8.3
EME version:2.4.50

**Additional context**
The last time somebody have paid for the membership was the 16 june 2024

**Comment by liedekef** [comment] 2024-07-17 18:23
I tried registering at your site and it redirected perfectly fine to stripe ...

**Comment by f14m07** [comment] 2024-07-17 18:28
Yes, it is true for the button at the end. But from the link in the msg after validation (orange background color) and the link in the welcome mail for this membership the button does'nt work

**Comment by liedekef** [comment] 2024-07-17 18:29
Ok, clicking on the link in the mail seems to fail. Based on the output from html, it seems the start-form tag is missing. I need to check this, because I can't reproduce that locally yet.

**Comment by liedekef** [comment] 2024-07-17 18:36
This html code seems wrong: 
`div id='eme-payment-form' class='eme-payment-form >&#8216;<br />Vous pouvez payer en ligne maintenant en cliquant sur le bouton ci-dessous.<form action='
`
Are you sure you're on the latest version ? The closing quote after the class-statement is missing, and that's exactly what I fixed in the latest release.

**Comment by liedekef** [comment] 2024-07-17 18:38
Correction: it seems some typo still remained ... weird, I'll check the git changes and if needed release a new version this evening.

**Comment by liedekef** [comment] 2024-07-17 18:49
Even more weird: locally I have the same typo but somehow my browser seems to correct it before displaying ????

Ok, found it: apparently I made the same typo 2 times (copy/paste): one for bookings, one for memberships. And I fixed it only for bookings it seems. So I'll release a new version.

**Comment by f14m07** [comment] 2024-07-17 18:51
Thanks Franky for your quick support. Happy you find the cause

**Comment by liedekef** [comment] 2024-07-17 18:55
ok, new version released

**Closed by liedekef** 2024-07-17 18:55 UTC
Labels: feedback required, not reproducable
